name: Deploy to Render
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Render
        run: curl -X POST https://api.render.com/deploy/specific-endpoint
